const LOAD_STUDENT_PROFILE_FULFILLED = 'LOAD_STUDENT_PROFILE_FULFILLED';
const LOAD_STUDENT_PROFILE = 'LOAD_STUDENT_PROFILE';
const LOAD_COURSE_FULFILLED = 'LOAD_COURSE_FULFILLED';
const LOAD_COURSE = 'LOAD_COURSE';
const LOAD_ASSIGNMENT_FULFILLED = 'LOAD_ASSIGNMENT_FULFILLED';
const LOAD_ASSIGNMENT = 'LOAD_ASSIGNMENT';
const LOAD_ASSIGNMENT_REVIEW_FULFILLED = 'LOAD_ASSIGNMENT_REVIEW_FULFILLED';
const LOAD_ASSIGNMENT_REVIEW = 'LOAD_ASSIGNMENT_REVIEW';

export default {
    LOAD_ASSIGNMENT,
    LOAD_ASSIGNMENT_FULFILLED,
    LOAD_ASSIGNMENT_REVIEW,
    LOAD_ASSIGNMENT_REVIEW_FULFILLED,
    LOAD_COURSE,
    LOAD_COURSE_FULFILLED,
    LOAD_STUDENT_PROFILE,
    LOAD_STUDENT_PROFILE_FULFILLED
}